## Задание 1

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив

In [5]:
import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat = mat*2
mat[mat>10]=0

print("Матрица с заменеными элементами ",'\n',  mat)

Матрица с заменеными элементами  
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [8]:
a = np.random.randint(1, 100, 20)
print(a, '\n')

print("Элеметы делящиеся нацело на пять", a[a%5==0], '\n')

a[a%5==0]=-1

print("Массив с заменеными элементами", a)

[18 78 59 60 62 61 45 82 25 78 78 93 50 16 97 15 89 77 64 54] 

Элеметы делящиеся нацело на пять [60 45 25 50 15] 

Массив с заменеными элементами [18 78 59 -1 62 61 -1 82 -1 78 78 93 -1 16 97 -1 89 77 64 54]


## Задание 3

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50.
Выведите все промежуточные и итоговые результаты.

In [11]:
mas = np.random.randint(0, 50, size = (1, 5))
mas1 = np.random.randint(0, 50, size = (1, 5))

result = np.vstack((mas, mas1))

b = result[0, :]
b1 = result[1, :]

print(result)
print()
print(b)
print(b1)


[[ 1 29  3 43 23]
 [38 46 46  5 23]]

[ 1 29  3 43 23]
[38 46 46  5 23]


## Задание 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [56]:
mas = np.random.uniform(-10, 10, 50)
print(mas, '\n')

summ=sum(mas)
sum_poz = sum(mas[mas>0])
sum_neg = sum(mas[mas<0]) 

print('Сумма = ', summ)
print('Сумма положительных = ', sum_poz)
print('Сумма отрицательных = ', sum_neg)

[-4.93111199 -4.80869981 -9.07360347  7.28128537  2.78192243 -6.70307785
  8.72978167 -8.18900149  4.58635835  7.82603653 -7.13372415  4.91349611
  9.06667619 -5.79353542  7.59630852  2.03498657  6.34292723 -7.9715842
  4.61570795 -3.28422346  6.66397245 -7.24985258  2.43724782 -7.87997808
  7.20468106  8.07533201 -2.7360095  -3.88051394 -2.97723749 -1.46521994
  8.75897691 -9.50043949  7.24938738  9.30807482  6.32312059 -1.38013331
 -5.78831508  7.16718262  8.48730592  7.55542741 -7.98891574  9.72876938
 -2.05232963 -3.14372429 -1.41885043  6.00638701  5.12699226  5.94629252
  7.46213119 -0.27997604] 

Сумма =  63.64671088294743
Сумма положительных =  179.27676826620566
Сумма отрицательных =  -115.63005738325823


## Задание 5

Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [58]:
mat = np.eye(4)
m = [5, 10, 15, 20]
m_diag = np.diag(m)
mat1 = np.array(m_diag)

sum_el_mat = np.sum(mat)
sum_el_mat1 = np.sum(mat)

print('Суммма  элементов матрицы a = ',sum_el_a) 
print('Суммма элементов мтарицы а1 = ', sum_el_a1)

Суммма  элементов матрицы a =  4.0
Суммма элементов мтарицы а1 =  50


## Задание 6

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [60]:
mat = np.random.randint(1, 20, size=(3, 3))  
mat1 = np.random.randint(1, 20, size=(3, 3))  

print('Сумма матриц',"\n",  mat + mat1, "\n")  
print('Разность матриц ', "\n", mat - mat1, "\n")  
print('Поэлементое произведение',"\n",  mat* mat1, "\n")

Сумма матриц 
 [[19 26 21]
 [ 6 30 26]
 [23  6  5]] 

Разность матриц  
 [[-7 10 13]
 [-2 -2 -6]
 [-7  2 -3]] 

Поэлементое произведение 
 [[ 78 144  68]
 [  8 224 160]
 [120   8   4]] 



## Задание 7

Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [62]:
mat1 = np.random.randint(1, 10, size = (2, 3))
mat2 = np.random.randint(1, 10, size = (3, 2))

print(mat1,'\n')
print(mat2, '\n')
print(np.dot(mat1, mat2))

[[2 5 8]
 [9 6 6]] 

[[5 1]
 [8 3]
 [8 2]] 

[[114  33]
 [141  39]]


## Задание 8

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы (используйте np.linalg.det).
Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [64]:
mat = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(mat)

if det == 0:
    print("матрица вырождена")

inv = np.linalg.inv(mat)
print('Определитель = ', det)
print('Oбратная матица ','\n', inv)

Определитель =  1655.0000000000002
Oбратная матица  
 [[-0.00181269 -0.01691843  0.08942598]
 [ 0.10151057 -0.05256798 -0.00785498]
 [-0.02477341  0.1021148  -0.11117825]]


## Задание 9

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу
Транспонированную матрицу
След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.

In [66]:
mat = np.random.randint(1, 50, size = (4,4))
trace = np.trace(mat)

print(mat, '\n')
print('Транспонированная матрица', '\n', np.transpose(mat), '\n')
print('След = ', trace)

[[35 42 45 37]
 [17 44 27 28]
 [36  3 27  9]
 [29 48  4 35]] 

Транспонированная матрица 
 [[35 17 36 29]
 [42 44  3 48]
 [45 27 27  4]
 [37 28  9 35]] 

След =  141


## Задание 10

Решите систему линейных уравнений вида:

\begin{equation*}
 \begin{cases}
   2x+3y-z=5, 
   \\
    4x-y+2z=6 ,
   \\
   -3x+5y+4z=-2.
 \end{cases}
\end{equation*}

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат


In [68]:
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


## Решите индивидуальное задание согласно вашему варианту (1). 
Распределение инвестиций. Компания выделила 1 000 000 рублей на три
проекта. Первый проект получает в два раза больше, чем второй, а третий
получает на 200 000 рублей больше, чем второй. Сколько денег получит
каждый проект?

Обозначим:
x — сумма для первого проекта,

y — сумма для второго проекта,

z — сумма для третьего проекта.

Уравнение 1: Общая сумма инвестиций
По условию, общая сумма распределяемых денег равна 1 000 000 рублей, поэтому:

x+y+z=1000000

Уравнение 2: Первый проект в 2 раза больше второго
Первый проект получает вдвое больше, чем второй, значит:

x=2y
Уравнение 3: Третий проект на 200 000 больше второго
Третий проект получает на 200 000 рублей больше, чем второй, значит:

z=y+200000

\begin{equation*}
 \begin{cases}
   x+y+z=1000000, 
   \\
    x=2y ,
   \\
   z=y+200000.
 \end{cases}
\end{equation*}

In [71]:
# решение матричным методом
A = np.array([[1,1,1], 
            [1, -2, 0], 
            [0, -1, 1]])
A_inv = np.linalg.inv(A)#обратная матрица
B = [1000000, 0, 200000]
X = np.dot(A_inv, B)
print(X[0], '- р на первый проект')
print(X[1], '- р на второй проект')
print(X[2], '- р на третий проект', '\n')

# Решение методом крамера
det_A = np.linalg.det(A)
A1 = A.copy()
A2 = A.copy()
A3 = A.copy()
# Заменяем столбцы на вектор B

A1[:, 0] = B   
A2[:, 1] = B  
A3[:, 2] = B  
#Вычисляем определители новых матриц
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
# находим иксы

x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
print(f"На первый проект выделено: {(x1)} р")
print(f"На второй проект выделено: {(x2)} р")
print(f"На второй проект выделено {(x3)} р", '\n')

#проверка третьим способом
print(np.linalg.solve(A, B))

400000.0 - р на первый проект
200000.0 - р на второй проект
400000.0 - р на третий проект 

На первый проект выделено: 399999.99999999953 р
На второй проект выделено: 200000.0000000001 р
На второй проект выделено 399999.99999999953 р 

[400000. 200000. 400000.]
