## Задание 1

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
все элементы массива на 2, а затем замените все элементы больше 10 на 0.
Выведите итоговый массив

In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = a*2
a[a>10]=0

print("Матрица с заменеными элементами ",'\n',  a)

Матрица с заменеными элементами  
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание 2

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
-1 и выведите обновленный массив

In [10]:
a = np.random.randint(1, 100, 20)
print(a, '\n')

print("Элеметы делящиеся нацело на пять", a[a%5==0], '\n')

a[a%5==0]=-1

print("Массив с заменеными элементами", a)

[ 8 94  6 50 29 80 68 64  8 96  1 10 54 38 63 93 27 47 95 31] 

Элеметы делящиеся нацело на пять [50 80 10 95] 

Массив с заменеными элементами [ 8 94  6 -1 29 -1 68 64  8 96  1 -1 54 38 63 93 27 47 -1 31]


## Задание 3

Создайте два массива NumPy размером 1×5, заполненные случайными числами
от 0 до 50. Объедините эти массивы в один двумерный массив (по строкам).
Разделите полученный массив на два массива, каждый из которых содержит 5
элементов.
Выведите все промежуточные и итоговые результаты.

In [12]:
a = np.random.randint(0, 50, size = (1, 5))
a1 = np.random.randint(0, 50, size = (1, 5))

result = np.vstack((a, a1))

b = result[0, :]
b1 = result[1, :]
print(a)
print(a1)
print()
print(result)
print()
print(b)
print(b1)


[[35 39 33 15 35]]
[[33 10 19 15  9]]

[[35 39 33 15 35]
 [33 10 19 15  9]]

[35 39 33 15 35]
[33 10 19 15  9]


## Задание 4

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [14]:
mas = np.random.uniform(-10, 10, 50)
print(mas, '\n')

summ=sum(mas)
sum_poz = sum(mas[mas>0])
sum_neg = sum(mas[mas<0]) 

print('Сумма = ', summ)
print('Сумма положительных = ', sum_poz)
print('Сумма отрицательных = ', sum_neg)

[ 9.03524462 -3.26969123 -3.25745107  6.80392695 -8.88344216 -4.26050089
  0.41495266 -2.16972721  9.1041067  -7.56523762  4.41926583  5.77643097
  5.88558894  8.78029171 -3.90098432  0.1450231   4.62002783  2.26650947
  7.07632466 -7.66611196 -2.15318127 -7.81433385 -5.13848509 -0.58423541
 -5.13331672 -2.77693557 -8.50901494  7.73316314  5.6092691  -1.33486575
  2.48200324 -2.35869625 -1.65932386  8.34395591 -7.62800414  1.84268091
 -2.44851871  5.60989361 -1.0048386  -1.62503183  6.00563725 -6.74065378
  4.5534051   5.61939095 -9.13338092 -8.43479113  7.53014742 -6.85599969
  1.40263694 -0.23712486] 

Сумма =  -1.4840018686122942
Сумма положительных =  121.05987698013521
Сумма отрицательных =  -122.54387884874751


## Задание 5

Создайте:
Единичную матрицу размером 4×4.
Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).
Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [16]:
a = np.eye(4)
m = [5, 10, 15, 20]
m_diag = np.diag(m)
a1 = np.array(m_diag)

sum_el_a = np.sum(a)
sum_el_a1 = np.sum(a1)

print('Суммма  элементов матрицы a = ',sum_el_a) 
print('Суммма элементов мтарицы а1 = ', sum_el_a1)

Суммма  элементов матрицы a =  4.0
Суммма элементов мтарицы а1 =  50


## Задание 6

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:
Их сумму
Их разность
Их поэлементное произведение

In [18]:
a = np.random.randint(1, 20, size=(3, 3))  
a1 = np.random.randint(1, 20, size=(3, 3))  

print('Сумма матриц',"\n",  a + a1, "\n")  
print('Разность матриц ', "\n", a - a1, "\n")  
print('Поэлементое произведение',"\n",  a * a1, "\n")

Сумма матриц 
 [[30 15  9]
 [35 33 31]
 [19 21 33]] 

Разность матриц  
 [[  4   5  -1]
 [  3  -1   1]
 [-13  -5  -3]] 

Поэлементое произведение 
 [[221  50  20]
 [304 272 240]
 [ 48 104 270]] 



## Задание 7

Создайте две матрицы NumPy:
Первую размером 2×3, заполненную случайными числами от 1 до 10.
Вторую размером 3×2, заполненную случайными числами от 1 до 10.
Выполните матричное умножение (используя оператор @ или функцию np.dot) и выведите результат.

In [20]:
matrix1 = np.random.randint(1, 10, size = (2, 3))
matrix2 = np.random.randint(1, 10, size = (3, 2))

print(matrix1,'\n')
print(matrix2, '\n')
print(np.dot(matrix1, matrix2))

[[4 4 2]
 [8 6 7]]

[[8 5]
 [5 2]
 [6 3]] 

[[ 64  34]
 [136  73]]


## Задание 8

Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
Определитель этой матрицы (используйте np.linalg.det).
Обратную матрицу (используйте np.linalg.inv). Если матрица вырождена (определитель равен 0), выведите сообщение, что матрица вырождена.

In [23]:
matrix = np.random.randint(1, 20, size=(3, 3))
det = np.linalg.det(matrix)

if det == 0:
    print("матрица вырождена")

inv = np.linalg.inv(matrix)
print('Определитель = ', det)
print('Oбратная матица ','\n', inv)

Определитель =  22.00000000000059
Oбратная матица  
 [[ -6.13636364  -4.5          9.18181818]
 [  8.95454545   6.5        -13.27272727]
 [ -4.95454545  -3.5          7.27272727]]


## Задание 9

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:
Исходную матрицу
Транспонированную матрицу
След матрицы (сумму элементов на главной диагонали)
Используйте np.trace для нахождения следа.

In [25]:
matrix = np.random.randint(1, 50, size = (4,4))
trace = np.trace(matrix)

print(matrix, '\n')
print('Транспонированная матрица', '\n', np.transpose(matrix), '\n')
print('След = ', trace)

[[18 14  4 25]
 [42 40  7 37]
 [ 8 36 10 42]
 [17 11 10 10]] 

Транспонированная матрица 
 [[18 42  8 17]
 [14 40 36 11]
 [ 4  7 10 10]
 [25 37 42 10]] 

След =  78


## Задание 10

Решите систему линейных уравнений вида:

\begin{equation*}
 \begin{cases}
   2x+3y-z=5, 
   \\
    4x-y+2z=6 ,
   \\
   -3x+5y+4z=-2.
 \end{cases}
\end{equation*}

Используйте матричное представление Ax = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат


In [27]:
A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = [5, 6, -2]

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


## Решите индивидуальное задание согласно вашему варианту (1). 
Распределение инвестиций. Компания выделила 1 000 000 рублей на три
проекта. Первый проект получает в два раза больше, чем второй, а третий
получает на 200 000 рублей больше, чем второй. Сколько денег получит
каждый проект?

Обозначим за y количество денег выделенных на 2 проект , за x и z - первый и третий соответственно

Сумма всех инвестиций должна быть равно 1000000 р. x + y + z = 1000000

Раз первый проект получает в 2 раза больше денег, соотвественно х = 2y,

так как третий проект получает на 200000 р. больше чем второй, последняя подсистема будет иметь вид z =y + 200000 

Итого получим систему следущего вида :

\begin{equation*}
 \begin{cases}
   x + y + z = 1000000, 
   \\
    х = 2y ,
   \\
   z =y + 200000 .
 \end{cases}
\end{equation*}

In [18]:
import numpy as np
# Создадим матрицу коэффициентов и вектор свободных членов
A = np.array([
    [1, 1, 1],    # x + y + z
    [1, -2, 0],    # x - 2y = 0
    [0, -1, 1]     # -y + z = 200 000
])

B = np.array([1000000, 0, 200000])

## Метод Крамера
def cramer_solve(A, B):
    det_A = np.linalg.det(A)
    solutions = []
    for i in range(A.shape[1]):
        Ai = A.copy()
        Ai[:, i] = B
        det_Ai = np.linalg.det(Ai)
        solutions.append(det_Ai / det_A)
    return solutions

cramer_solution = cramer_solve(A, B)
print(f"Решение методом Крамера: {cramer_solution}")

## Матричный метод (A^(-1)*B)
matrix_solution = np.linalg.inv(A) @ B
print(f"Решение матричным методом: {matrix_solution}")

## Linalg.solve
numpy_solution = np.linalg.solve(A, B)
print(f"Решение np.linalg.solve: {numpy_solution}")

## Проверка решений
print("\nСравнение решений:")
print(f"Метод Крамера и np.linalg.solve: {np.allclose(cramer_solution, numpy_solution)}")
print(f"Матричный метод и np.linalg.solve: {np.allclose(matrix_solution, numpy_solution)}")

## Интерпретация результатов
x, y, z = numpy_solution
print("\nРаспределение инвестиций:")
print(f"Первый проект (x): {x:.2f} руб.")
print(f"Второй проект (y): {y:.2f} руб.")
print(f"Третий проект (z): {z:.2f} руб.")

Решение методом Крамера: [399999.99999999953, 200000.0000000001, 399999.99999999953]
Решение матричным методом: [400000. 200000. 400000.]
Решение np.linalg.solve: [400000. 200000. 400000.]

Сравнение решений:
Метод Крамера и np.linalg.solve: True
Матричный метод и np.linalg.solve: True

Распределение инвестиций:
Первый проект (x): 400000.00 руб.
Второй проект (y): 200000.00 руб.
Третий проект (z): 400000.00 руб.
